WITH C as(
    SELECT MEMBER_ID, count(*) as cnt
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
),
D as (
    SELECT MEMBER_ID
    from C
    WHERE cnt = (select max(cnt) from C)
)
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE A
JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID IN (SELECT MEMBER_ID FROM D)
order by B.REVIEW_DATE, B.REVIEW_TEXT;

