
WITH A AS (
  SELECT ITEM_ID, ITEM_NAME, RARITY
  FROM ITEM_INFO 
  WHERE RARITY = 'RARE'
),
B AS (
  SELECT ITEM_TREE.ITEM_ID
  FROM ITEM_TREE 
  JOIN A ON ITEM_TREE.PARENT_ITEM_ID = A.ITEM_ID
)
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
FROM ITEM_INFO, B
WHERE ITEM_INFO.ITEM_ID = B.ITEM_ID
ORDER BY B.ITEM_ID DESC;
